import { ModuleNode } from '../../resolver/types';
import { TransformOutput } from '../types';

/**
 * The "CSS-in-JS extractor" transform named in the brief: a `.css` file has no JS AST,
 * so instead of running it through the JsPlugin pipeline, we synthesize a small runtime
 * module whose job is to inject the original CSS text into the document via a <style>
 * tag the first time it's required, then export an (empty, in this simplified version)
 * class-name map. This makes `import './styles.css'` in a browser bundle a real,
 * working side-effecting import instead of a bundler error on an unknown extension.
 *
 * Documented simplification: unlike the JS/JSX transform, this fully synthesizes new
 * code rather than editing the original text in place, so there is no line-accurate
 * source map back into the .css file — the generated module is attributed to the file
 * as a whole via a leading comment instead.
 */
export function transformCss(node: ModuleNode): TransformOutput {
  const styleId = `nirman-style-${simpleHash(node.id)}`;
  const code = [
    `// Generated by Nirman's CSS-in-JS extractor plugin from ${JSON.stringify(node.id)}`,
    `var __css = ${JSON.stringify(node.source)};`,
    `if (typeof document !== "undefined") {`,
    `  var __existing = document.getElementById(${JSON.stringify(styleId)});`,
    `  if (!__existing) {`,
    `    var __el = document.createElement("style");`,
    `    __el.id = ${JSON.stringify(styleId)};`,
    `    __el.textContent = __css;`,
    `    document.head.appendChild(__el);`,
    `  }`,
    `}`,
    `module.exports = {};`,
    ``,
  ].join('\n');

  return { code, map: null };
}

function simpleHash(input: string): string {
  let h = 0;
  for (let i = 0; i < input.length; i++) {
    h = (Math.imul(31, h) + input.charCodeAt(i)) | 0;
  }
  return Math.abs(h).toString(36);
}
